export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECT_FAIL = "FETCH_PROJECT_FAIL";
export const SET_PROJECT_FILTER = "SET_PROJECT_FILTER";

export const FETCH_INFO_START = "FETCH_INFO_START";
export const FETCH_INFO_SUCCESS = "FETCH_INFO_SUCCESS";
export const FETCH_INFO_FAIL = "FETCH_INFO_FAIL";

export const FETCH_POSITIVE_START = "FETCH_POSITIVE_START";
export const FETCH_POSITIVE_SUCCESS = "FETCH_POSITIVE_SUCCESS";
export const FETCH_POSITIVE_FAIL = "FETCH_POSITIVE_FAIL";

export const POST_POSITIVE_START = "POST_POSITIVE_START";
export const POST_POSITIVE_SUCCESS = "POST_POSITIVE_SUCCESS";
export const POST_POSITIVE_FAIL = "POST_POSITIVE_FAIL";
export const OPEN_POSITIVE_FORM = "OPEN_POSITIVE_FORM";
export const CLOSE_POSITIVE_FORM = "CLOSE_POSITIVE_FORM";